# ----
# Site

title: Foto Costiui
url: "https://foto.costiui.ml"
baseurl: "https://foto.costiui.ml"
google_analytics_key: "UA-147213854-2"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Foto Costiui Fotogafi Costiui.
author:
  name:
  email:
  twitter:
social:
  name: Foto Costiui
  links:
    - https://github.com/Costiui/foto.costiui.net
    - https://www.facebook.com/CostiuiNet
    - https://twitter.com/costiui
    - https://www.youtube.com/channel/UCvZo-Y043ipjefFW9ONGJ8A
    - https://costiui.tumblr.com
    - https://vimeo.com/costiui
    - https://www.instagram.com/costiui.ronaszek

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /images/_screenshot.png
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
